version: 2.1

executors:
  playwright-executor:
    docker:
      - image: mcr.microsoft.com/playwright:v1.21.0-focal  # Docker image con Playwright preinstalado
    working_directory: ~/repo

jobs:
  test:
    executor: playwright-executor
    steps:
      - checkout  # Esto descarga el código desde GitHub
      - run:
          name: Install dependencies
          command: |
            npm install
      - run:
          name: Run tests
          command: |
            npm test

workflows:
  version: 2
  test:
    jobs:
      - test
